# Generated by Django 3.2.8 on 2021-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethiotravel', '0003_best_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='intros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
