# Generated by Django 3.2.8 on 2021-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethiotravel', '0004_intros'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('testimonies', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
