# Generated by Django 3.2.8 on 2021-10-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethiotravel', '0006_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
