# Generated by Django 3.2.8 on 2021-11-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethiotravel', '0007_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='detail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
